#×¢²áÖĞĞÄÅäÖÃ
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8010/eureka/
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/

