server:
  port: 9999

spring:
  application:
    name: silicon-oss-web
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      test:
        url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&allowMultiQueries=true&allowLoadLocalInfile=true
        username: root
        password: 123456
      # 从库数据源
      test1:
        url: jdbc:mysql://127.0.0.1:3306/test1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&allowMultiQueries=true&allowLoadLocalInfile=true
        username: root
        password: 123456
      minIdle: 5
      maxActive: 200
      initialSize: 5
      timeBetweenEvictionRunsMillis: 3000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'ZTM' FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

# 配置pagehelper参数
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

