server:
  port: 8020
spring:
  application:
    name: func-service
  jmx:
    default-domain: func-service
  zipkin:
    base-url: http://127.0.0.1:8080
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
      name: config
      profile: test
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

#注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8010/eureka/
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1

task:
  queue:
    corePoolSize: 10
    maxPoolSize: 30
    queueCapacity: 8
    keepAlive: 60


#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
##############################



#  datasource:
#    name: mybatis_test
#        #使用druid连接池
#    type: com.alibaba.druid.pool.DruidDataSource
#        #druid相关配置
#    druid:
#          #监控统计拦截的filters
#      filters: stat
#      driver-class-name: com.mysql.jdbc.Driver
#          #配置基本属性
##      url: jdbc:mysql://localhost/work_platform?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=CTT
#      url: jdbc:mysql://192.168.0.220/topo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=CTT
##      url: jdbc:mysql://122.16.115.39:3306/work_platform?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=CTT
#      username: root
#      password: 123456
#          #配置初始化大小/最小/最大
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#          #获取连接等待超时时间
#      max-wait: 60000
#          #间隔多久进行一次检测，检测需要关闭的空闲连接
#      time-between-eviction-runs-millis: 60000
#          #一个连接在池中最小生存的时间
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#           #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20
#
#mybatis:
#  # 映射文件所在路径
#  mapper-locations: classpath:mappers/*.xml

#  mapper-locations: classpath:mappers/*.xml

#线程池配置
#task:
#  queue:
#    corePoolSize: 10
#    maxPoolSize: 30
#    queueCapacity: 8
#    keepAlive: 60